# One key for global values ('global'), one for nodes ('nodes')
---
global:
  # For now, you can only override local values, meaning in case this key already exists, it's overwritten
  override:
    # This will result in all nodes having both Google DNS servers set
    dns:
      - 8.8.8.8
      - 8.8.4.4
nodes:
  -
    hostname: node1.example.org
    ip: 1.2.3.4
    subnet: 24
    dns:
      - 8.8.8.8
    nodename: node1
    pubkeys:
      - ssh-ed25519 ...
      - ssh-rsa ...
    flannelnet: 10.1.0.0/16
    kubernetes:
      kubeuser:
        pubkeys:
          - ssh-rsa ...
          - ssh-ed25519 ...
    includes:
      1st: node1.include_1.yaml
      2nd: node1.include_2.yaml
  -
    hostname: node2.example.org
    ip: 2.3.4.5
    dns:
      - 8.8.8.8
    nodename: node2
    pubkeys:
      - ssh-ed25519 ...
      - ssh-rsa ...
    flannelnet: 10.2.0.0/16
    kubernetes:
      kubeuser:
        pubkeys:
          - ssh-rsa ...
          - ssh-ed25519 ...
    includes:
      1st: node2.include_1.yaml
  -
    hostname: node3.example.org
    ip: 3.4.5.6
    subnet: 24
    dns:
      - 8.8.8.8
    nodename: node3
    pubkeys:
      - ssh-ed25519 ...
      - ssh-rsa ...
    flannelnet: 10.3.0.0/16
    kubernetes:
      kubeuser:
        pubkeys:
          - ssh-rsa ...
          - ssh-ed25519 ...